### ISSUE TITLE
opensea link is not identical with Loot bag id.

### ISSUE THREAD

**Issue by kwanlae** [lootproject/website#119]
opensea link, for example https://opensea.io/assets/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7/1337 is not the same with the Loot bag id #1337.

To resolve this, I think useEffect in React Hook can be used.

**Comment by thsnyzkn** [comment]
Hello,
Thanks for bringing it up, but I doubt that this problem is not related with this website.
Did you mean that the listing on OpenSea is wrong, or something else?
Could you care to elaborate more please? I am going to close the issue, if it is needed please re-open.

**Comment by kwanlae** [comment]
In the website, Example Bag says 111, but the link of that bag is https://opensea.io/assets/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7/ **1337**  instead of https://opensea.io/assets/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7/ **111** 

Whenever refresh the page, the situation is changed. The browser inspection says "Warning: Text content did not match", so I think this seems to be the React Hook issue.
