### ISSUE TITLE
Link does not match #id.

### ISSUE THREAD

**Issue by dhkkim** [lootproject/website#126]
![image](https://user-images.githubusercontent.com/18570908/134833123-d8f6fc6e-005e-4114-b1fb-a5ffe0537ab9.png)

Links on index does not match correct id number.

**Comment by thsnyzkn** [comment]
It is due to the content of the following file: https://github.com/lootproject/website/blob/main/utils/constants.ts

I could just change it by looking at the respective id's content or we could try something else to retrieve the specific loots' content?
@domhofmann @ravindranrahul

**Comment by ravindranrahul** [comment]
@thsnyzkn Thanks for taking time to fix this :)
