### ISSUE TITLE
MLoot support

### ISSUE THREAD

**Issue by pietromingo** [lootproject/website#61]
is it possible to add resources for Mloot as well?

**Comment by ravindranrahul** [comment]
My understanding is that its a seperate project. @domhofmann @Anish-Agnihotri  thoughts?

**Comment by pietromingo** [comment]
I think Loot and Mloot are part of the same project, otherwise what sense would MLoot make?

**Comment by alanionita** [comment]
What resources are you thinking? How to mint, how check rarity, etc?

**Comment by pietromingo** [comment]
> What resources are you thinking? How to mint, how check rarity, etc?

Yes, the tools that support both Loot and mLoot for example. 
Also enter the link to the contract for mLoot and explain what it is

**Comment by alanionita** [comment]
These should set you up @pietromingo 

## mLoot Rarity
* helps you find bags
* check rarity in the bag / of the items
* you can preview bags
* search for items

https://admiring-lumiere-a0df27.netlify.app/#/927839

## True Rarity
* contains lists of items
* useful if you want to find a specific class of item and then use the above to find a bag that has it

https://github.com/Kolo9/True-Rarity
